#!/bin/sh

# Download PC版拼音挂接/百度小鹤.zip from http://flypy.ys168.com/
# Run ./generate-flypy-yinxing-dict.sh 百度小鹤.zip

zip="$1"

dict="flypy_yinxing.dict.yaml"

cat > "$dict" <<EOF
# Rime dict
# encoding: utf-8
#
# 小鹤音形 http://flypy.com/
#
# Generated by Azuwis using generate-flypy-yinxing-dict.sh

---
name: flypy_yinxing
version: "2015.5.19"
sort: original
use_preset_vocabulary: false
columns:
  - code
  - text
...

EOF

unzip -p "$zip" 百度小鹤/百度小鹤.txt \
    | iconv -f UTF16 -t UTF8 \
    | fromdos \
    | sed -e '/\$/d' -e '/=\//d' -e 's/^[0-9]\+,//' -e 's/=/\t/' \
    >> "$dict"
