#!/bin/sh

# Download PC版拼音挂接/百度小鹤.zip from http://flypy.ys168.com/
# Run:
#     ./update-flypy.sh 百度小鹤.zip

zip="$1"

dict="flypy.upstream.dict.yaml"

version=$(unzip -l "$zip" | awk '/百度小鹤.txt/ {print $2}' | sed 's/-/\./g')

cat > "$dict" <<EOF
# Rime dict
# encoding: utf-8
#
# 小鹤音形 http://flypy.com/
#
# Generated by Zhong Jianxin using $0

---
name: flypy.upstream
version: "${version}"
sort: original
use_preset_vocabulary: false
columns:
  - code
  - text
encoder:
  rules:
    - length_equal: 2
      formula: "AaAbBaBb"
    - length_equal: 3
      formula: "AaBaCaCb"
    - length_in_range: [4, 10]
      formula: "AaBaCaZa"
...

EOF

unzip -p "$zip" 百度小鹤/百度小鹤.txt \
    | iconv -f UTF16 -t UTF8 \
    | fromdos \
    | sed -e '/\$/d' -e '/=\//d' -e 's/^[0-9]\+,//' -e 's/=/\t/' \
    >> "$dict"
