#!/bin/sh

# Download 西风瘦码.7z from http://yunpan.cn/QCy5Ak9ZM5zya (code 3500)
# Run:
#     ./xfsm.sh 西风瘦码.7z

archive="$1"

name="xfsm"
dict="${name}.dict.yaml"

version=$(7z l "$archive" | awk '/西风瘦码.txt/ {print $1}' | sed 's/-/\./g')

cat > "$dict" <<EOF
# Rime dict
# encoding: utf-8
#
# 西风瘦码 http://tieba.baidu.com/f?kw=%CE%F7%B7%E7%CA%DD%C2%EB
#
# Generated by Zhong Jianxin using $0

---
name: ${name}
version: "${version}"
sort: original
use_preset_vocabulary: false
columns:
  - code
  - text
...
EOF

7z e -so "$archive" 西风瘦码/.yong/mb/西风瘦码.txt \
    | iconv -f GB18030 -t UTF8 \
    | fromdos \
    | sed -e '1,/^\[DATA\]/d' -e '/\$/d' -e 's/ /\t/' \
          >> "$dict"

7z e -so "$archive" 西风瘦码/.yong/mb/user2.txt \
    | iconv -f GB18030 -t UTF8 \
    | fromdos \
    | sed -e '/config/d' -e '/^oj;/d' -e '/^oz/d' -e 's/\$LEFT//' -e '/\$/d' -e 's/ /\t/' \
          >> "$dict"
