#!/bin/sh

# Download 哲哲豆音形码/哲豆音形大圆满版词库___多多格式.txt from http://zzdzzd.ys168.com/
# Run:
#     ./zzd.sh 哲豆音形大圆满版词库___多多格式.txt 2015.12.14

table="$1"
version=$2

dict="zzd.dict.yaml"

cat > "$dict" <<EOF
# Rime dict
# encoding: utf-8
#
# 哲哲豆音形码 http://zzdzzd.ys168.com/
#
# Generated by Zhong Jianxin using $0

---
name: zzd
version: "${version}"
sort: original
use_preset_vocabulary: false
columns:
  - text
  - code
encoder:
  rules:
    - length_equal: 2
      formula: "AaAbBaBb"
    - length_equal: 3
      formula: "AaAbBaCa"
    - length_in_range: [4, 10]
      formula: "AaBaCaZa"
...

EOF

cat "$table" \
    | iconv -f UTF16 -t UTF8 \
    | fromdos \
    >> "$dict"
